section_start("ccache")

set(CCACHE_WEBSITE "https://ccache.dev/")

sage_options(ADD CCACHE_ENABLED DOC "Use [`ccache`](${CCACHE_WEBSITE}) to speedup subsequent compilations" INIT ON)
if (SAGE_OPT_CCACHE_ENABLED)
	if (NOT ${CMAKE_BUILD_TYPE} STREQUAL "Debug")
		message(WARNING "Consider using ccache only for Debug builds")
	endif()

	find_program(CCACHE ccache)
	if (CCACHE)
		set(CXX_COMPILER_LAUNCHER ${CCACHE})
		set(C_COMPILER_LAUNCHER ${CCACHE})
		section_pass("${CCACHE}")
	else()
		set(SAGE_OPT_CCACHE_ENABLED OFF)
		message(WARNING "Unable to find `ccache` program, you may acquire it through ${CCACHE_WEBSITE} or your system's package manager")
		section_fail("${CCACHE}")
	endif()
else()
	unset(CXX_COMPILER_LAUNCHER)
	unset(C_COMPILER_LAUNCHER)
	if (${CMAKE_BUILD_TYPE} STREQUAL "Debug")
		message(WARNING "Consider configuring cmake with `-DSAGE_OPT_CCACHE_ENABLED=ON`")
	endif()
	section_pass("Skip")
endif()

